server {
    listen 80;
    server_name your-ec2-public-ip-or-domain;

    client_max_body_size 25M;

    location /static/ {
        alias /home/ubuntu/campusconnect/app/static/;
        expires 30d;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/ubuntu/campusconnect/campusconnect.sock;
    }
}
