"""Create all CampusConnect tables

Revision ID: 8d9adce9e5ac
Revises: 
Create Date: 2026-09-07 22:14:31.284697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9adce9e5ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backup_type', sa.Enum('DATABASE', 'FILES', name='backup_type'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='backup_status'), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('size_mb', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contributions_user_id'), ['user_id'], unique=False)

    op.create_table('note_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'FULFILLED', name='request_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_requests_semester'), ['semester'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_requests_subject'), ['subject'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('faculty', sa.String(length=100), nullable=True),
    sa.Column('keywords', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status'), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_approval_status'), ['approval_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_keywords'), ['keywords'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_semester'), ['semester'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_title'), ['title'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('placement_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.Enum('APTITUDE', 'CODING', 'INTERVIEW', 'HR', 'RESUME', 'MATERIALS', name='placement_section'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('external_link', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('placement_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_placement_resources_section'), ['section'], unique=False)

    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_downloads_note_id'), ['note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_downloads_user_id'), ['user_id'], unique=False)

    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempts_quiz_id'), ['quiz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_questions_quiz_id'), ['quiz_id'], unique=False)

    op.create_table('request_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('responder_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['note_requests.id'], ),
    sa.ForeignKeyConstraint(['responder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.String(length=255), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_options_question_id'), ['question_id'], unique=False)

    op.create_table('quiz_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['quiz_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_answers_attempt_id'), ['attempt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_answers_attempt_id'))

    op.drop_table('quiz_answers')
    with op.batch_alter_table('quiz_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_options_question_id'))

    op.drop_table('quiz_options')
    op.drop_table('request_replies')
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_questions_quiz_id'))

    op.drop_table('quiz_questions')
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_quiz_id'))

    op.drop_table('quiz_attempts')
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_downloads_user_id'))
        batch_op.drop_index(batch_op.f('ix_downloads_note_id'))

    op.drop_table('downloads')
    op.drop_table('quizzes')
    with op.batch_alter_table('placement_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_placement_resources_section'))

    op.drop_table('placement_resources')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_title'))
        batch_op.drop_index(batch_op.f('ix_notes_subject'))
        batch_op.drop_index(batch_op.f('ix_notes_semester'))
        batch_op.drop_index(batch_op.f('ix_notes_keywords'))
        batch_op.drop_index(batch_op.f('ix_notes_department'))
        batch_op.drop_index(batch_op.f('ix_notes_approval_status'))

    op.drop_table('notes')
    with op.batch_alter_table('note_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_requests_subject'))
        batch_op.drop_index(batch_op.f('ix_note_requests_status'))
        batch_op.drop_index(batch_op.f('ix_note_requests_semester'))

    op.drop_table('note_requests')
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contributions_user_id'))

    op.drop_table('contributions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('categories')
    op.drop_table('backup_logs')
    # ### end Alembic commands ###
